### ISSUE TITLE
怎样调用百度翻译的api

### ISSUE THREAD

**Issue by PDragon-code** [machangxin/Auk-s-Translation#1]
你好，想问下你使用HttpURLConnection实现网络请求收发的具体代码是在哪个文件里

**Comment by msk397** [comment]
/home
<https://github.com/machangxin/Auk-s-Translation/tree/master/app/src/main/java/com/auk/fanyi/ui/home>
/HomeFragment.java
给个Star哦亲😀

PDragon-code <notifications@github.com> 于2020年6月8日周一 下午11:48写道：

**Comment by PDragon-code** [comment]
好嘞
